<<<<<<< HEAD
spring.application.name=Week7
=======
# Server port configuration
server.port=8080

# Spring boot configurations
spring.main.banner-mode=off
>>>>>>> 2b3c29fcb4421e8ce42a90cf79ee610b6688bdf3
